# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/ed6d0ca6-f498-4dde-b3db-a3fa44451b32";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/7E65-C25A";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  fileSystems."/mnt/C:" =
    { device = "/dev/disk/by-uuid/904E60224E5FFF7A";
      fsType = "ntfs";
    };

  fileSystems."/mnt/NVME" =
    { device = "/dev/disk/by-uuid/FEBE7F63BE7F12FF";
      fsType = "ntfs";
    };

  fileSystems."/mnt/SSD" =
    { device = "/dev/disk/by-uuid/7404D7E804D7AAFE";
      fsType = "ntfs";
    };

  fileSystems."/mnt/Czwarty" =
    { device = "/dev/disk/by-uuid/B642967642963B57";
      fsType = "ntfs";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/41118c18-a7a5-446d-85f7-37945aa07c74"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
