{
  config,
  pkgs,
  lib,
  ...
}: {
  nixpkgs.config.allowUnfree = true;
  # Import other configuration modules
  # (hardware-configuration.nix is autogenerated upon installation)
  # paths in nix expressions are always relative the file which defines them
  imports = [
    ./hardware-configuration.nix
    ./music.nix
    ./tailscale.nix
  ];
  time.timeZone = "Europe/Warsaw";
  # Name your host machine
  networking = {
    hostName = "nixserver";
    networkmanager.enable = true;
    interfaces.eth0.ipv4.addresses = [
      {
        address = "192.168.0.183";
        prefixLength = 24;
      }
    ];
    nftables.enable = true;
    enableIPv6 = lib.mkForce false;
    firewall = {
      enable = true;
      allowedTCPPorts = [443 80 22 4533];
      allowedUDPPorts = [config.services.tailscale.port];
    };
    defaultGateway = "192.168.1.1";
    useDHCP = lib.mkForce false;
    nameservers = [
      "8.8.8.8"
      "8.8.4.4"
      "1.1.1.1"
      "1.0.0.1"
      "208.67.222.222"
      "208.67.220.220"
      "4.2.2.1"
      "4.2.2.2"
      "8.26.56.26"
      "8.20.247.20"
      "149.112.112.112"
      "9.9.9.9"
      "9.9.9.10"
      "149.112.112.10"
      "149.112.112.11"
      "9.9.9.11"
    ];
  };
  networking.networkmanager.connectionConfig = {
    "ipv6.method" = "ignore";
    "ipv6.never-default" = "true";
  };

  boot.loader.grub.enable = true;
  services.logind.settings.Login = {
    HandleLidSwitch = "ignore";
    HandleLidSwitchExternalPower = "ignore";
    HandleLidSwitchDocked = "ignore";
  };

  boot.loader.grub.devices = ["/dev/sda"];
  # Define user accounts
  users.users.rysieko = {
    extraGroups = ["wheel" "networkmanager"];
    isNormalUser = true;
    shell = pkgs.nushell;
  };

  # Install some packages
  environment.systemPackages = with pkgs; [
    neovim
    git
    wget
    curl
    btop
    nh
  ];
  nix.settings.experimental-features = ["nix-command" "flakes"];
  # Enable the OpenSSH daemon
  services.openssh.enable = true;
  nix.settings.trusted-users = ["192.168.0.141" "rysieko@nixsolvesthis"];
  system.stateVersion = "26.05"; # DO NOT TOUCH YOU FUCKING IDIOT
}
