{
  config,
  pkgs,
  ...
}: {
  # Import other configuration modules
  # (hardware-configuration.nix is autogenerated upon installation)
  # paths in nix expressions are always relative the file which defines them
  imports = [
    ./hardware-configuration.nix
    ./pihole.nix
    ./mc.nix
  ];
  time.timeZone = "Europe/Warsaw";
  # Name your host machine
  networking = {
    hostName = "nixserver";
    networkmanager.enable = true;
    interfaces.eth0.ipv4.addresses = [
      {
        address = "192.168.0.183";
        prefixLength = 24;
      }
    ];
    firewall = {
      enable = true;
      allowedTCPPorts = [443 80 22];
    };
    defaultGateway = "192.168.1.1";
    useDHCP = false;
    nameservers = [
      "8.8.8.8"
      "8.8.4.4"
      "1.1.1.1"
      "1.0.0.1"
      "208.67.222.222"
      "208.67.220.220"
      "4.2.2.1"
      "4.2.2.2"
      "8.26.56.26"
      "8.20.247.20"
      "149.112.112.112"
      "9.9.9.9"
      "9.9.9.10"
      "149.112.112.10"
      "149.112.112.11"
      "9.9.9.11"
    ];
  };
  boot.loader.limine.enable = true;
  boot.loader.limine.biosSupport = true;
  boot.loader.limine.biosDevice = "/dev/sda";
  # Define user accounts
  users.users.rysieko = {
    extraGroups = ["wheel" "networkmanager"];
    isNormalUser = true;
  };

  # Install some packages
  environment.systemPackages = with pkgs; [
    nvim
    git
    wget
    curl
    btop
  ];

  # Enable the OpenSSH daemon
  services.openssh.enable = true;
  system.stateVersion = "26.05"; # DO NOT TOUCH YOU FUCKING IDIOT
}
