# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sr_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-amd"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/e15e1723-4f21-4c3d-a4f6-1e234b37c70d";
    fsType = "btrfs";
    options = ["subvol=@"];
  };

  fileSystems."/srv" = {
    device = "/dev/disk/by-uuid/e15e1723-4f21-4c3d-a4f6-1e234b37c70d";
    fsType = "btrfs";
    options = ["subvol=@srv"];
  };

  fileSystems."/root" = {
    device = "/dev/disk/by-uuid/e15e1723-4f21-4c3d-a4f6-1e234b37c70d";
    fsType = "btrfs";
    options = ["subvol=@root"];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/e15e1723-4f21-4c3d-a4f6-1e234b37c70d";
    fsType = "btrfs";
    options = ["subvol=@home"];
  };

  fileSystems."/var/cache" = {
    device = "/dev/disk/by-uuid/e15e1723-4f21-4c3d-a4f6-1e234b37c70d";
    fsType = "btrfs";
    options = ["subvol=@cache"];
  };

  fileSystems."/var/log" = {
    device = "/dev/disk/by-uuid/e15e1723-4f21-4c3d-a4f6-1e234b37c70d";
    fsType = "btrfs";
    options = ["subvol=@log"];
  };

  fileSystems."/var/tmp" = {
    device = "/dev/disk/by-uuid/e15e1723-4f21-4c3d-a4f6-1e234b37c70d";
    fsType = "btrfs";
    options = ["subvol=@tmp"];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/2D31-CF03";
    fsType = "vfat";
    options = ["fmask=0022" "dmask=0022"];
  };

  swapDevices = [];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
